DROP SCHEMA IF EXISTS `DoAn_202`;
CREATE SCHEMA `DoAn_202`;
USE `DoAn_202`;

CREATE TABLE `USER`(
  `USERNAME` VARCHAR(100) PRIMARY KEY NOT NULL,
  `PWD` VARCHAR(100)
);
CREATE TABLE `HOUSE`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `URL_IMG` VARCHAR(100),
  `USERNAME` VARCHAR(100),
  FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ROOM`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `URL_IMG` VARCHAR(100),
  `HOUSE_ID` BIGINT,
  `TEMPERATURE` BOOLEAN DEFAULT FALSE,
  `GAS` BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (HOUSE_ID) REFERENCES HOUSE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `LED`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `VALUE` BOOLEAN,
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `FAN`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `VALUE` BOOLEAN,
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `user` VALUES('hieupham', '123');
INSERT INTO `house` (`house`.`NAME`, `house`.`URL_IMG`, `house`.`USERNAME`) VALUES('abc', 'abc', 'hieupham');
INSERT INTO `room`(`room`.`NAME`, `room`.`URL_IMG`, `room`.`HOUSE_ID`, `room`.`TEMPERATURE`, `room`.`GAS`) VALUES('abc', 'abc', 1, 1, 1);