DROP SCHEMA IF EXISTS `DoAn_212`;
CREATE SCHEMA `DoAn_212`;
USE `DoAn_212`;

CREATE TABLE `USER`(
  `USERNAME` VARCHAR(100) PRIMARY KEY NOT NULL,
  `PWD` VARCHAR(100)
);
CREATE TABLE `HOUSE`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `URL_IMG` VARCHAR(100),
  `USERNAME` VARCHAR(100),
  FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ROOM`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `URL_IMG` VARCHAR(100),
  `HOUSE_ID` BIGINT,
  `TEMPERATURE` BOOLEAN DEFAULT FALSE,
  `GAS` BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (HOUSE_ID) REFERENCES HOUSE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `LED`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `VALUE` BOOLEAN,
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `FAN`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `VALUE` BOOLEAN,
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `NOTIFY`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(100),
  `VALUE` INT,
  `TIME` date
);

INSERT INTO `user` VALUES('hieupham', '123');

INSERT INTO `house` (`house`.`NAME`, `house`.`URL_IMG`, `house`.`USERNAME`) 
VALUES('Nhà 1', 'default', 'hieupham');

INSERT INTO `room`(`room`.`NAME`, `room`.`URL_IMG`, `room`.`HOUSE_ID`, `room`.`TEMPERATURE`, `room`.`GAS`) 
VALUES('Phòng 1', 'default', 1, 1, 1),
('Phòng 2', 'default', 1, 1, 1),
('Phòng cuối', 'default', 1, 1, 1);

INSERT INTO `led`(`led`.`NAME`, `led`.`VALUE`, `led`.`ROOM_ID`) 
VALUES ("Đèn 1", 0, 1);

INSERT INTO `fan`(`fan`.`NAME`, `fan`.`VALUE`, `fan`.`ROOM_ID`) 
VALUES ("Quạt đứng", 0, 1);

INSERT INTO `notify`(`notify`.`CONTENT`, `notify`.`VALUE`, `notify`.`TIME`) VALUES
("Nhà 1@phòng 1", 800, "2022-04-18");