DROP SCHEMA IF EXISTS `DoAn_202`;
CREATE SCHEMA `DoAn_202`;
USE `DoAn_202`;

CREATE TABLE `USER`(
  `USERNAME` VARCHAR(100) PRIMARY KEY NOT NULL,
  `PWD` VARCHAR(100)
);
CREATE TABLE `HOUSE`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `URL_IMG` VARCHAR(100),
  `USERNAME` VARCHAR(100),
  FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ROOM`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `URL_IMG` VARCHAR(100),
  `HOUSE_ID` BIGINT,
  `TEMPERATURE` BOOLEAN DEFAULT FALSE,
  `GAS` BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (HOUSE_ID) REFERENCES HOUSE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `LED`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `VALUE` BOOLEAN,
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `FAN`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `VALUE` BOOLEAN,
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `METHOD_HOUSE`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `HOUSE_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `DEVICE_IN_HOUSE_METHOD`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DEVICE_NAME` VARCHAR(100),
  `VALUE` BOOLEAN DEFAULT FALSE,
  `METHOD_ID` BIGINT,
  FOREIGN KEY (METHOD_ID) REFERENCES METHOD_HOUSE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `METHOD_ROOM`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100),
  `ROOM_ID` BIGINT,
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `DEVICE_IN_ROOM_METHOD`(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `DEVICE_NAME` VARCHAR(100),
  `VALUE` BOOLEAN DEFAULT FALSE,
  `METHOD_ID` BIGINT,
  FOREIGN KEY (METHOD_ID) REFERENCES METHOD_ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `user` VALUES('hieupham', '123');